# Generated by Django 4.1.3 on 2022-12-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicapp', '0002_alter_empadress_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empadress',
            name='Country',
            field=models.CharField(choices=[('1', 'india'), ('2', 'USA')], max_length=50),
        ),
    ]
