# Generated by Django 4.1.3 on 2022-12-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicapp', '0004_alter_empadress_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empadress',
            name='Country',
            field=models.CharField(choices=[('USA', 'USA'), ('INDIA', 'INDIA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='empadress',
            name='Massage',
            field=models.TextField(max_length=160, unique=True),
        ),
    ]
