# Generated by Django 4.1.3 on 2022-12-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicapp', '0010_alter_empadress_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empadress',
            name='Massage',
            field=models.TextField(max_length=160, unique=True),
        ),
    ]
