# Generated by Django 4.1.3 on 2022-12-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicapp', '0011_alter_empadress_massage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empadress',
            name='Country',
            field=models.CharField(choices=[('USA', 'USA'), ('INDIA', 'INDIA')], max_length=50),
        ),
    ]
