# Generated by Django 4.1.3 on 2022-12-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicapp', '0012_alter_empadress_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empadress',
            name='Country',
            field=models.CharField(choices=[('INDIA', 'INDIA'), ('USA', 'USA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='empadress',
            name='Massage',
            field=models.TextField(max_length=160),
        ),
    ]
